import type { FinisherDefinition } from "./types";

export const FINISHER_LIBRARY: FinisherDefinition[] = [
  {
    id: "pump-delts",
    name: "Delts Pump Circuit",
    type: "pump",
    rounds: 3,
    intensity: "moderate",
    equipment: ["dumbbells", "cable"],
    notes: "Lateral raise + rear delt + front raise.",
  },
  {
    id: "pump-arms",
    name: "Arms Pump Finisher",
    type: "pump",
    rounds: 3,
    intensity: "moderate",
    equipment: ["cable", "dumbbells"],
    notes: "Curl + pressdown + overhead ext.",
  },
  {
    id: "pump-chest",
    name: "Chest Pump 6-Min",
    type: "pump",
    durationMinutes: 6,
    intensity: "moderate",
    equipment: ["machine", "dumbbells"],
    notes: "Machine press + flye.",
  },
  {
    id: "pump-back",
    name: "Back Pump Ladder",
    type: "pump",
    durationMinutes: 8,
    intensity: "moderate",
    equipment: ["cable", "machine"],
  },
  {
    id: "pump-legs",
    name: "Legs Pump Burn",
    type: "pump",
    durationMinutes: 8,
    intensity: "hard",
    equipment: ["machine"],
  },
  {
    id: "cond-sled",
    name: "Sled Pushes",
    type: "conditioning",
    durationMinutes: 10,
    intensity: "hard",
    equipment: ["sled"],
  },
  {
    id: "cond-bike",
    name: "Bike Intervals",
    type: "conditioning",
    durationMinutes: 8,
    intensity: "hard",
    equipment: ["bike"],
    notes: ":30 on / :90 off.",
  },
  {
    id: "cond-row",
    name: "Row Intervals",
    type: "conditioning",
    durationMinutes: 10,
    intensity: "hard",
    equipment: ["rower"],
  },
  {
    id: "cond-incline",
    name: "Incline Walk",
    type: "conditioning",
    durationMinutes: 12,
    intensity: "easy",
    equipment: ["treadmill"],
  },
  {
    id: "core-abwheel",
    name: "Ab Wheel + Plank",
    type: "core",
    rounds: 3,
    intensity: "moderate",
    equipment: ["ab wheel"],
  },
  {
    id: "core-cable",
    name: "Cable Crunch Circuit",
    type: "core",
    rounds: 3,
    intensity: "moderate",
    equipment: ["cable"],
  },
  {
    id: "core-planks",
    name: "Plank Series",
    type: "core",
    rounds: 2,
    intensity: "easy",
    equipment: ["bodyweight"],
  },
  {
    id: "mobility-hips",
    name: "Hip Mobility Flow",
    type: "mobility",
    durationMinutes: 8,
    intensity: "easy",
    equipment: ["bodyweight"],
  },
  {
    id: "mobility-shoulders",
    name: "Shoulder Opener",
    type: "mobility",
    durationMinutes: 8,
    intensity: "easy",
    equipment: ["band"],
  },
  {
    id: "mobility-tspine",
    name: "T-Spine Mobility",
    type: "mobility",
    durationMinutes: 10,
    intensity: "easy",
    equipment: ["foam roller"],
  },
  {
    id: "carry-farmer",
    name: "Farmer Carry",
    type: "carry",
    durationMinutes: 6,
    intensity: "moderate",
    equipment: ["dumbbells"],
  },
  {
    id: "carry-suitcase",
    name: "Suitcase Carry",
    type: "carry",
    durationMinutes: 6,
    intensity: "moderate",
    equipment: ["kettlebell"],
  },
];

